- name: zfir.dev
  description: Personal portfolio website
  tag: "portfolio"
  api:
    method: GET
    url: https://zfir.dev
- name: blog.zfir.dev
  description: Personal blog
  tag: "blog"
  api:
    method: GET
    url: https://blog.zfir.dev
- name: l.zfir.dev
  description: URL shortener
  tag: "url-shortener"
  api:
    method: GET
    url: https://l.zfir.dev/D2Xzywy
- name: vpn.zfir.dev
  description: VPN service
  tag: "vpn"
  api:
    method: GET
    url: https://vpn.zfir.dev
